import os

def creationDico():
    dictionnaire = {
                    "wPawn1": "a2",
                    "wPawn2": "b2",
                    "wPawn3": "c2",
                    "wPawn4": "d2",
                    "wPawn5": "e2",
                    "wPawn6": "f2",
                    "wPawn7": "g2",
                    "wPawn8": "h2",
                    "bPawn1": "a7",
                    "bPawn2": "b7",
                    "bPawn3": "c7",
                    "bPawn4": "d7",
                    "bPawn5": "e7",
                    "bPawn6": "f7",
                    "bPawn7": "g7",
                    "bPawn8": "h7",
                    "wRook1": "a1",
                    "wKnight1": "b1",
                    "wBishop1": "c1",
                    "wQueen0": "d1",
                    "wKing0": "e1",
                    "wBishop2": "f1",
                    "wKnight2": "g1",
                    "wRook2": "h1",
                    "bRook1": "a8",
                    "bKnight1": "b8",
                    "bBishop1": "c8",
                    "bQueen0": "d8",
                    "bKing0": "e8",
                    "bBishop2": "f8",
                    "bKnight2": "g8",
                    "bRook2": "h8",
    }
    return dictionnaire
